# Generated by Django 4.2 on 2025-08-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='account_holder',
            field=models.CharField(default='husband', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='bank_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
