# Generated by Django 4.2 on 2025-08-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0002_uploadedfile_account_holder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#808080', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='parser_api.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, unique=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('regex', 'Regular Expression')], default='contains', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_learning', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='parser_api.category')),
            ],
            options={
                'ordering': ['-confidence', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('original_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('account_holder', models.CharField(max_length=20)),
                ('bank_type', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('category_confidence', models.FloatField(default=0.0)),
                ('manually_categorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser_api.category')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parser_api.processingsession')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parser_api.uploadedfile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionpattern',
            index=models.Index(fields=['pattern'], name='parser_api__pattern_b177c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpattern',
            index=models.Index(fields=['is_active'], name='parser_api__is_acti_0110b4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='parser_api__date_ddc072_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['description'], name='parser_api__descrip_a2bf93_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_holder'], name='parser_api__account_7867da_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bank_type', 'account_type'], name='parser_api__bank_ty_04441b_idx'),
        ),
    ]
