# Generated by Django 4.2 on 2025-11-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0003_category_transactionpattern_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=10),
        ),
    ]
