# Generated by Django 4.2 on 2025-11-13 00:34

from django.db import migrations


def migrate_account_holders_forward(apps, schema_editor):
    """Convert existing account_holder strings to AccountHolder objects"""
    AccountHolder = apps.get_model('parser_api', 'AccountHolder')
    UploadedFile = apps.get_model('parser_api', 'UploadedFile')
    Transaction = apps.get_model('parser_api', 'Transaction')

    # Create AccountHolder objects for each unique account_holder value
    holder_map = {}

    # Get unique account_holder values from UploadedFile
    unique_holders = set(
        UploadedFile.objects.values_list('account_holder', flat=True).distinct()
    )
    # Get unique account_holder values from Transaction
    unique_holders.update(
        Transaction.objects.values_list('account_holder', flat=True).distinct()
    )

    # Color mapping for common holder names
    color_map = {
        'husband': '#3498db',  # Blue
        'spouse': '#e74c3c',   # Red
        'default': '#95a5a6',  # Gray
    }

    # Create AccountHolder objects
    for holder_name in unique_holders:
        if holder_name and holder_name not in holder_map:
            # Capitalize first letter for display
            display_name = holder_name.capitalize()
            color = color_map.get(holder_name.lower(), '#808080')
            is_default = (holder_name.lower() == 'default' or holder_name.lower() == 'husband')

            account_holder, created = AccountHolder.objects.get_or_create(
                name=display_name,
                defaults={'color': color, 'is_default': is_default}
            )
            holder_map[holder_name] = account_holder

    # If no default holder exists, create one
    if not AccountHolder.objects.filter(is_default=True).exists():
        default_holder, _ = AccountHolder.objects.get_or_create(
            name='Default',
            defaults={'color': '#95a5a6', 'is_default': True}
        )

    # Migrate UploadedFile records
    for uploaded_file in UploadedFile.objects.all():
        if uploaded_file.account_holder in holder_map:
            uploaded_file.account_holder_fk = holder_map[uploaded_file.account_holder]
            uploaded_file.save(update_fields=['account_holder_fk'])

    # Migrate Transaction records
    for transaction in Transaction.objects.all():
        if transaction.account_holder in holder_map:
            transaction.account_holder_fk = holder_map[transaction.account_holder]
            transaction.save(update_fields=['account_holder_fk'])


def migrate_account_holders_reverse(apps, schema_editor):
    """Reverse migration - copy account_holder_fk back to account_holder string"""
    UploadedFile = apps.get_model('parser_api', 'UploadedFile')
    Transaction = apps.get_model('parser_api', 'Transaction')

    # Restore account_holder string from account_holder_fk
    for uploaded_file in UploadedFile.objects.all():
        if uploaded_file.account_holder_fk:
            uploaded_file.account_holder = uploaded_file.account_holder_fk.name.lower()
            uploaded_file.save(update_fields=['account_holder'])

    for transaction in Transaction.objects.all():
        if transaction.account_holder_fk:
            transaction.account_holder = transaction.account_holder_fk.name.lower()
            transaction.save(update_fields=['account_holder'])


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0005_accountholder_transaction_account_holder_fk_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_account_holders_forward, migrate_account_holders_reverse),
    ]
