# Generated by Django 4.2 on 2025-11-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0006_migrate_account_holder_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('regex', 'Regular Expression')], default='contains', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Merchant Patterns',
                'ordering': ['-confidence', 'pattern'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant_name'], name='parser_api__merchan_8c21fa_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantpattern',
            index=models.Index(fields=['pattern'], name='parser_api__pattern_71b857_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantpattern',
            index=models.Index(fields=['is_active'], name='parser_api__is_acti_856b9a_idx'),
        ),
    ]
